pipeline {
    agent any

    tools {
        maven 'M2_HOME' // Ensure the Maven installation name matches your Jenkins configuration
        jdk 'JAVA_HOME'         // Ensure the JDK installation name matches your Jenkins configuration
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/raviguru-git/amz-rgp.git', branch: 'master'
            }
        }

        stage('Build') {
            steps {
                dir('product') {
                    echo 'Building the project...'
                    bat 'mvn clean install -X'
                }
            }
        }

        stage('Test') {
            steps {
                dir('product') {
                    echo 'Running tests...'
                    bat 'mvn test -X'
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
