pipeline {
    agent any

    tools {
        maven 'Maven' // Assuming Maven is configured as 'Maven' in Jenkins
        jdk 'JDK8' // Assuming JDK is configured as 'JDK8' in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Allure Report') {
            steps {
                allure includeProperties: false, jdkInstallation: 'JDK8', results: [[path: 'target/allure-results']]
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            junit '**/target/surefire-reports/*.xml'
        }
        failure {
            mail to: "<INSERT_YOUR_EMAIL>",
                 subject: "Build Failed: ${currentBuild.fullDisplayName}",
                 body: "Build details: ${env.BUILD_URL}"
        }
    }
}