pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout your code from your source control
                git 'https://github.com/raviguru-git/amz-rgp.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the project...'
                // Add your build command, e.g., for Maven
                bat 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                // Run your tests
                bat 'mvn test'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}